server:
  servlet:
    context-path: /rabbitmq-message-listener
management:
  server:
    port: 8081
    servlet:
      context-path: /rabbitmq-message-listener
  endpoints:
    web:
      base-path: /


spring:
  rabbitmq:
    host: localhost
    port: 5672
    userName: guest
    password: guest
    exchange: employee
    queue: Employee_Queue
    routing-key: employee.routingkey

validCustomerTypes:  Permanent,Contract,Internal